
services:
  app:
    build: .
    container_name: hotel-booking-app
    env_file:
      - .env
    environment:
      - SERVER_PORT=8386
    ports:
      - "8386:8386"
    networks:
      - hotel-booking-network

networks:
  hotel-booking-network:
    driver: bridge
